services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A src.pipeline worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" 